MongoAuth: Allow custom data when creating new user.
eclipse-vertx/vertx-auth pull request #111
Opened 2016-12-18 14:59 UTC by DieterDePaepe

Issue #102.

2016-12-18 19:28 UTC, pmlopes commented
I believe we should pass the ‘IllegalArgumentException‘ to the handler instead of throwing to avoid try catch blocks while using the API.

2016-12-18 23:36 UTC, stefanvitz commented
I agree with pmlopes. the change looks fine but an handle(Future.failedFuture..)  would most likely be my choice here as well.

2016-12-19 10:22 UTC, DieterDePaepe commented
I'd disagree. This kind of error is a programming error and not a program execution error, and therefor an immediate IllegalArgumentException seems best. I'd imagine any programmer keeping some kind of schema of their data model (of what is being put into mongo), so it is at this stage that they should take care that no fields overlap. They shouldn't be caught at runtime, but discovered in advance using tests.

2016-12-19 10:30 UTC, pmlopes commented
You can still return the typed exception in the future:

```java
Future.failedFuture(new IllegalArgumentException(reason));
```

this makes the code cleaner in the sense you only need:

```
mongo.createUser( ... res -> {
  if (res.failed()) {
    // do something, probably inspect the type of the cause
    if (res.cause() instanceof IllegalArgumentException) {
      // handle this is a special way...
    }
  } else {
    // everything went fine!
  }
});
```

Instead of:

```java
try {
  mongo.insertUser(... res -> {
    if (res.failed()) {
      // handle error (1)
    } else {
      // everything went fine!
    }
  });
} catch (IllegalArgumentException e) {
  // handle error (2) for this case...
}
```

In the second case you need to handle errors in 2 places using 2 different notations and it can be tricky once you have a bunch of async calls and users get confused if the top level try catch will catch errors from the handlers (which it won't).

2016-12-19 12:09 UTC, DieterDePaepe commented
You may have misunderstood me. I'm arguing that this is a type of error that shouldn't be caught at all, similar as how you would not write checks for NullPointerException everywhere in the code. If this error occurs, it is a programming bug, not a recoverable error.

Further argumentation why it is a programming bug, based on my own usage of this library: I am storing users in mongo, the structure of a user in the mongo collection is my responsibility. Therefor I should make that there are no conflicting keys between my own structure of a user and the username/password/roles/permissions fields that I am passing to MongoAuth.

See also the responses to [this stackoverflow question](http://stackoverflow.com/questions/15208544/when-should-an-illegalargumentexception-be-thrown).

2016-12-19 12:23 UTC, pmlopes commented
I understand the reasoning of runtime exceptions and agree however due to the async model of vert.x if you throw a runtime exception it won't unwind the stack to a state your application crashes or your current request is terminated but leaves it in a intermediate state since no one will call the request to terminate. In these cases what will happen is that a request will stall until there is a socket timeout and you won't have any way to either terminate it or handle it.

By passing it to the future you can later on ignore it or handle it as you want...

2016-12-19 12:23 UTC, stefanvitz commented
ok... so your argumentation here would be: the programmer has to ensure the right format of the json before passing it. 
im not quite sure. i assume it depends how you create the template json object. If it is dynamicly created the programmer perhaps does not know the exact content. Not catching the IllegalArgumentException that could cause hassle in your code... 
while the usage of the handler would result in an failure that you could handle normally..

Normally i just want my defines flow to complete flawlessy...  an unchecked exception because the content of an json object was not checked can really mess that up

2016-12-19 12:38 UTC, pmlopes commented
You can still write code assuming that there are no errors like:

```java
mongo.createUser( ... res -> {
  // everything went fine (maybe)! 
  res.result().someMethod(); // might throw NPE if there was a IllegalArgumentException during creation
});
```

2016-12-19 12:55 UTC, DieterDePaepe commented
@stefanvitz how does that differ from having to check whether you're not going to run into a NullPointerException for some variable that you dynamically determined? Just as the programmer might know that a certain method returns null (and having to check that before continuing to use that value), a programmer should know that a certain method might return keys that overlap with the predefined username/password/... keys.

@pmlopes for the last code fragment, you'd also get a timeout in case of an error, right? (And anyway, you cannot assume everything went right at that point, since problems might occur with the database. )

2016-12-31 13:41 UTC, DieterDePaepe commented
Any updates on this? I still prefer the original way I implemented this, but I'm willing to make the change to get this PR accepted. I think I've made my point, so I'll leave the final decision to you guys.

2017-01-09 19:19 UTC, pmlopes commented
@DieterDePaepe you should use the async result way instead of exception because it will help also how the codegen project will then work out the API to be usable from `RX`, `CompletableFuture`s and so on. By keeping it in that style users who prefer RX will get the new API for "free" thanks to codegen.

(sorry for a late comment, was on vacation until yesterday ;))

2017-02-02 21:42 UTC, DieterDePaepe commented
Updated as requested.

2017-02-03 09:33 UTC, pmlopes commented on vertx-auth-mongo/src/main/java/io/vertx/ext/auth/mongo/impl/MongoAuthImpl.java
> +      Future.failedFuture(new IllegalArgumentException("Salt and password field should not be specified."));
shouldn't this be:
```java
if (...) {
  resultHandler.handle(Future.failedFuture(new IllegalArgumentException("Salt and password field should not be specified.")));
  return;
}
```

Otherwise how will you get the exception?

2017-02-03 09:33 UTC, pmlopes commented on vertx-auth-mongo/src/main/java/io/vertx/ext/auth/mongo/impl/MongoAuthImpl.java
> +        Future.failedFuture(new IllegalArgumentException("Conflicting values for username."));
same as before...

2017-02-03 09:35 UTC, pmlopes requested changes
We also need some test to cover the failure cases.

2017-02-03 09:35 UTC, pmlopes commented on vertx-auth-mongo/src/main/java/io/vertx/ext/auth/mongo/impl/MongoAuthImpl.java
> +        Future.failedFuture(new IllegalArgumentException("Conflicting values for roles."));
same as before...

2017-02-03 09:35 UTC, pmlopes commented on vertx-auth-mongo/src/main/java/io/vertx/ext/auth/mongo/impl/MongoAuthImpl.java
> +        Future.failedFuture(new IllegalArgumentException("Conflicting values for permissions."));
same as before...

2017-02-04 12:35 UTC, DieterDePaepe commented
Guess I shouldn't work on this when I'm tired! Fixed and added tests.

2018-03-07 10:01 UTC, pmlopes commented
Due to the fact that GDPR is being enforced soon (https://github.com/vert-x3/vertx-auth/pull/184/commits/4f17ba25e22e7ca9b6748a4ae1c25c06b6ece1ca) we should be neutral about personal identifiable data, as the Eclipse Vert.x projects does not want to be liable for any infringements.

For this reason I'll have to close this reject without merging as if it would be merged we would need to implement way more features, like, selective erasure, log erasure + eviction, data exports, etc...

2018-03-07 10:01 UTC, closed without merging