Fixes #120
eclipse-vertx/vertx-auth pull request #126
Opened 2017-03-30 18:18 UTC by pmlopes

2017-03-30 18:28 UTC, pmlopes commented
Related to: https://github.com/vert-x3/vertx-auth/pull/126

2017-04-03 08:57 UTC, tsegismont requested changes

2017-04-03 08:57 UTC, tsegismont commented on vertx-auth-common/src/main/java/io/vertx/ext/auth/impl/ChainAuthImpl.java
> +    new Handler<Integer>() {
Could you reorganize this code, adding a new private method to the class for calling the next provider? It is not obvious when you read the code why there's anonymous handler created.

2017-04-03 08:57 UTC, tsegismont commented on vertx-auth-common/src/main/java/io/vertx/ext/auth/impl/ChainAuthImpl.java
> +          resultHandler.handle(Future.failedFuture("No more providers"));
Can we make this message more informative? It's not clear that the message comes from the auth provider chain.

2017-04-03 10:25 UTC, tsegismont approved these changes

2017-04-05 11:37 UTC, merged