Context secure PRNG + docs
eclipse-vertx/vertx-auth pull request #131
Opened 2017-04-06 09:24 UTC by pmlopes

This is a proposal for a vertx context secure PRNG similar to Java's ThreadLocalRandom.

The rationale behind this is that random numbers are used in several places in the project, e.g.:

* Mongo Auth
* Mail Client
* Vertx-web CSRF
* Vertx-web htdigest
* SockJS Base Transport
* JDBC Auth
* Web Session store's
* Web Session
* plus users might also use random numbers in their apps

We know that SecureRandom is a blocking API if there is not enough entropy, so having a PRNG for each of these handlers will consume some entropy plus resources. Using this alternative approach there will be a max of 1 PRNG per vert.x context.

2017-04-11 09:59 UTC, tsegismont requested changes

2017-04-11 09:59 UTC, tsegismont commented on vertx-auth-common/src/main/java/io/vertx/ext/auth/VertxContextRandom.java
> +   * Get or create a secure non blocking random number generator using the current vert.x context. This method will not
`current` / `provided`

2017-04-11 09:59 UTC, tsegismont commented on vertx-auth-common/src/main/java/io/vertx/ext/auth/VertxContextRandom.java
> +    PRNG random = context.get(VertxContextRandom.class.getName());
Why not use \_\__.vertx.sthg_ as with do with other internal stuff?

2017-04-11 09:59 UTC, tsegismont commented on vertx-auth-common/src/main/java/io/vertx/ext/auth/VertxContextRandom.java
> +public interface VertxContextRandom {
Call it PRNG not Random. Otherwise it sound like a simple ThreadLocalRandom

2017-04-11 10:02 UTC, tsegismont commented
> plus users might also use random numbers in their apps

I wouldn't make this a general purpose recommendation. If users need a simple random they should use the tools available in their language.

Could you please show an example of Javascript code which would benefit from this change?

2017-05-04 12:22 UTC, pmlopes commented
The asciidocs now include an example for all generated languages. It shows that one can generate random Strings and Ints using the same API for all languages.

2017-05-11 13:12 UTC, tsegismont approved these changes

2017-05-11 13:13 UTC, merged