feat: added otp module with hotp auth implementation
eclipse-vertx/vertx-auth pull request #488
Opened 2021-06-14 10:56 UTC by otricadziziusz

### Motivation:

I create sub module auth-otp with implement HOTP(rfc4226) authentication. I want share with vertx community and a little bit later want support TOTP(rfc6238) authenticator.
Module support Google Authenticator with base32 key and qr codes. Could set auth attempts limit and resynchronization counter.

2021-06-14 13:34 UTC, pmlopes commented on vertx-auth-otp/pom.xml
> +      <version>generate_strings-SNAPSHOT</version>
This is a blocker for a final release, we can only release non snapshots

2021-06-14 13:35 UTC, pmlopes commented on vertx-auth-otp/pom.xml
> +    <dependency>
Is this dependency always required? My assumption (which may be wrong) is that QR codes are not always required, in this case we could mark this dependency optional, specially when it is mostly used on a UI side, not strictly necessary this kind of module.

2021-06-14 13:40 UTC, pmlopes commented on vertx-auth-otp/pom.xml
> +  <repositories>
Current release rules with the eclipse foundation, prevent us from using other sources than maven central, can we workaround this?

2021-06-14 13:42 UTC, pmlopes commented on vertx-auth-otp/src/main/java/examples/hotp/HotpAuthExamples.java
> +    try(FileOutputStream fos = new FileOutputStream("otp_key.png")) {
This can be problematic for a vert.x application as `FileOutputStream` is a blocking operation, can we get the `byte[]` data directly? If we can we should wrap this functionality with the API and return a vert.x Buffer so it can be used with the asynchronous APIs.

2021-06-14 13:43 UTC, pmlopes commented on vertx-auth-otp/src/main/java/examples/hotp/HotpAuthExamples.java
> +    JsonObject principal = new JsonObject() {{
`JsonObject` has a fluent API, so you don't need to do `{{ ... }}`. you can skip them.

2021-06-14 13:44 UTC, pmlopes commented on vertx-auth-otp/src/main/java/examples/hotp/HotpAuthExamples.java
> +    authProvider.requestHotp(new UserImpl(principal), userAsyncResult -> {});
The recommended way to use the API is to use the factory method in the public interfaces, so instead of `new UserImpl()` you should replace it with: `User.create()`

2021-06-14 13:46 UTC, pmlopes commented on vertx-auth-otp/src/main/java/examples/hotp/HotpAuthExamples.java
> +    authProvider.requestHotp(new UserImpl(principal), userAsyncResult -> {});
`requestHotp()` should be renamed with `authenticate()`, this way is adheres to the parent interface and we have a common API to perform authentication. Also if the user requires custom parameters, I think we should have a `Credentials` implementation, like for example in the `HTDigest` module.

2021-06-14 13:47 UTC, pmlopes commented on vertx-auth-otp/src/main/java/examples/hotp/HotpAuthExamples.java
> +    JsonObject credentials = new JsonObject() {{
Also if the user requires custom parameters, I think we should have a Credentials implementation, like for example in the HTDigest module.

2021-06-14 13:48 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/hotp/HotpAuth.java
> +  @GenIgnore
You should not `GenIgnore`, otherwise other languages (e.g.: Kotlin, Groovy, RX, JavaScript) will not see this method. You can solve it, by using `User` in the param instead of `UserImpl`.

2021-06-14 13:49 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/hotp/HotpAuth.java
> +  @GenIgnore
Same comment as in the previous method.

2021-06-14 13:55 UTC, pmlopes commented
@otricadziziusz great contribution! Your PR is in very good shape, there are a few comments added. My main concern atm is the use of non released dependencies to maven central which can be problematic to adhere to the eclipse foundation release process, plus the generation of QR codes, seems to be a blocking task which can be a problem.

Perhaps we should move the QR code to a vert.x web handler instead? Finally the use of BASE32 as byte[] isn't a big deal per se, but we probably should hide it behind a vert.x buffer so we can interop with all the code generators and languages.

2021-06-14 15:17 UTC, otricadziziusz commented
@pmlopes Thanks for review.

About a version of dependynce. The author of the library with OTP generator for now has not release the version with the desired feature, I have fork a repo and explicitly indicated the branch with the desired feature. Yes, now I understand what could be the problem. I could replace this dependency and just use reference implementation from RFC. I think this will be true solution.

I agree with the comment about the QR code, now I think about remove generation QR code. After all, there is only a URI inside it, which is generated through an io.vertx.ext.auth.otp.utils.AuthenticatorUriGenerator. URI will be enough to get the QR code with any convenient library.

About HotpAuth.requestHotp, it is now used as a supplier critical information 
for check otp challenge. I think about mechanism supply information for auth and revoke request otp authentication.

I am starting to work on your comments and perhaps in the process I will contact you here with questions or discussion?

2021-06-16 17:30 UTC, otricadziziusz commented
@pmlopes, I am finished working on comments, i replaced the dependency with the reference implementation from RFC4226. But, I need a hint about buffer. As I understand it, I need to change the encoding base32 for key on user. I am unable to place it in json due to io.vertx.core.json.DecodeException. I think that now, except use encoding, one cannot put key in json.

2021-06-16 18:11 UTC, pmlopes commented
@otricadziziusz thanks! I'll have a new look tomorrow in the morning... In the meantime it would be great to see how this module would work with vertx-web, perhaps a small helper handler could be created to perform 2FA tasks? Say return the QR code PNG, validate code (after user it authenticated) etc...

2021-06-16 18:45 UTC, otricadziziusz commented
Yes of course! I will do it shortly.

2021-06-17 10:30 UTC, pmlopes requested changes
I've a few comments. If you like and it would make it easier, I could merge the PR as is into a seperate branch, so I could also contribute with the small fixes, instead of asking you to do all the work.

I can imagine that you would want to do it all by yourself, but if you want some help, don't fell shy to let me know and we can work together that way!

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/main/java/org/openauthentication/otp/OneTimePasswordAlgorithm.java
> +package org.openauthentication.otp;
To keep the generated final jar compatible with JPMS we must hold all code under the module package, e.g.:

```
package io.vertx.ext.auth.otp.impl.org.openauthentication.otp;
```

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/utils/AuthenticatorUriGenerator.java
> +public class AuthenticatorUriGenerator {
We should annotate this with `@VertxGen` this would allow it to be used from polyglot contexts. This also means that the code should be slightly different:

```
@VertxGen
public interface AuthenticatorUriGenerator {
```

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/utils/AuthenticatorUriGenerator.java
> +  public static URI generateHotpUri(OtpKey otpKey, String label, String user, String issuer) {
Making it polyglot will cause problems with `URI` so it would require a `@GenIgnore(GenIgnore.PERMITED_TYPE)`

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/utils/OtpKey.java
> +public class OtpKey implements SecretKey {
This one also should be transformed to:

```
@VertxGen
public interface OtpKey {
```

And the implementation then can implement both `OtpKey` and `SecretKey` as keeping `SecretKey` in the top level interface would fail the generation.

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/utils/OtpKeyGenerator.java
> +public class OtpKeyGenerator {
Same `@VertxGen`.

Basically all public APIs should be annotated, anything that is implementation should go under a `impl` package and there there's no need to annotate.

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/pom.xml
> +    <dependency>
Instead of the core test dependency, you should use:
```xml
<dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-unit</artifactId>
      <scope>test</scope>
    </dependency>
``` 

Which means that tests should be slightly changed later on

2021-06-17 10:30 UTC, pmlopes commented on vertx-auth-otp/src/test/java/io/vertx/ext/auth/otp/HotpAuthOptionsTest.java
> +public class HotpAuthOptionsTest extends VertxTestBase {
Comming from the dependency change in the pom you can just do:

```java
@RunWith(VertxUnitRunner.class)
public class HotpAuthOptionsTest {

  @Rule
  public RunTestOnContext rule = new RunTestOnContext();

  @Test
  public void test1(TestContext should) {
...
```

If you test requires asynchronous calls your 1st line in the test is:

```java
 final Async test = should.async();
```

So you can now do all assertions against the `should` object, and signal that you're done with `test.complete()`.

2021-06-17 19:09 UTC, otricadziziusz commented
Thanks! I made changes that separate public api and implementation.

I agree, if it is more convenient for us then we could merge the PR into a separate branch. Yes, I would not mind your help.

2021-06-21 21:16 UTC, otricadziziusz commented
@pmlopes I am want starting to do examples work with module and would like to find out. In what form would it be more convenient to present an example of work module with vertx-web?

2021-06-22 11:59 UTC, pmlopes commented
@otricadziziusz I think the best way to do this is first we create a PoC of a webapp (nothing fancy), mostly get the basic concepts working, say for example:

1. create a properties auth with a test user
2. a form to register otp + the qr code
3. a confirm creation page where the 1st code is tested and the necessary data is stored (memory for now)
4. a login page that use the properties initially with a simple form
5. a second page where after login you enter the generated code and we can validate

Once we have all this working we can see how to isolate the OTP web handler code into a single class. WDYT?

2021-06-23 12:11 UTC, pmlopes commented
@otricadziziusz I've created the following test app:

```java
package org.acme;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.User;
import io.vertx.ext.auth.otp.OtpKey;
import io.vertx.ext.auth.otp.OtpKeyGenerator;
import io.vertx.ext.auth.otp.hotp.HotpAuth;
import io.vertx.ext.auth.otp.hotp.HotpAuthOptions;
import io.vertx.ext.auth.otp.hotp.HotpCredentials;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.handler.BodyHandler;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class Foo extends AbstractVerticle {

    static class DBEntry {
        final String id;
        final OtpKey key;
        int counter;

        DBEntry(String id, OtpKey key) {
            this.id = id;
            this.key = key;
        }
    }

    public static void main(String[] args) {
        Vertx.vertx().deployVerticle(new Foo());
    }

    private final Map<String, DBEntry> DB = new HashMap<>();

    @Override
    public void start() {

        OtpKeyGenerator keyGen = OtpKeyGenerator.create();
        HotpAuth hotp = HotpAuth.create(new HotpAuthOptions());

        Router app = Router.router(vertx);
        // for form data parsing
        app.route().handler(BodyHandler.create());

        app.get("/api")
                .handler(ctx -> ctx.json(new JsonObject().put("message", "Welcome to the two factor authentication exmaple")));

        app.post("/api/register")
                .handler(ctx -> {
                    String id = UUID.randomUUID().toString();

                    String path = "/user/" + id;
                    // Create temporary secret until it it verified
                    OtpKey temp_secret = keyGen.generate();
                    // Create user in the database
                    DB.put(path, new DBEntry(id, temp_secret));
                    // Send user id and base32 key to user
                    ctx.json(new JsonObject()
                            .put("id", id)
                            .put("secret", temp_secret.getBase32()));
                });

        app.post("/api/verify")
                .handler(ctx -> {
                    String userId = ctx.getBodyAsJson().getString("userId");
                    String token = ctx.getBodyAsJson().getString("token");

                    // Retrieve user from database
                    String path = "/user/" + userId;

                    DBEntry entry = DB.get(path);

                    JsonObject principal = new JsonObject()
                            .put("identifier", entry.id)
                            .put("key", entry.key.getBase32())
                            .put("counter", entry.counter);

                    hotp.requestHotp(User.create(principal), requestHotp -> {
                        if (requestHotp.failed()) {
                            ctx.fail(requestHotp.cause());
                        } else {
                            hotp.authenticate(new HotpCredentials(userId, token))
                                    .onFailure(ctx::fail)
                                    .onSuccess(user -> {
                                        // Update user data
                                        ctx.json(new JsonObject().put("verified", true));
                                    });
                        }
                    });
                });

        vertx.createHttpServer()
                .requestHandler(app)
                .listen(8080)
                .onFailure(Throwable::printStackTrace)
                .onSuccess(server -> {
                    System.out.println("Server listening: http://localhost:" + server.actualPort());
                });
    }
}
```

Can you check if this is correct?

2021-06-23 19:00 UTC, otricadziziusz commented
@pmlopes Thanks for creating the example! I checked this example, the only first code works for me. Since the current example does not save information about the counter to the database and it is always 0. All following generated codes will be invalid.

2021-06-23 19:03 UTC, pmlopes commented
@otricadziziusz which app do you use ? I was trying to use freeotp but even the first code fails. Must I use Google authenticator instead?

2021-06-23 19:06 UTC, otricadziziusz commented
```
package org.acme;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.User;
import io.vertx.ext.auth.otp.AuthenticatorUriGenerator;
import io.vertx.ext.auth.otp.OtpKey;
import io.vertx.ext.auth.otp.OtpKeyGenerator;
import io.vertx.ext.auth.otp.hotp.HotpAuth;
import io.vertx.ext.auth.otp.hotp.HotpAuthOptions;
import io.vertx.ext.auth.otp.hotp.HotpCredentials;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.handler.BodyHandler;

import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;

public class Foo extends AbstractVerticle {

  static class DBEntry {
    final String id;
    final OtpKey key;
    int counter;

    DBEntry(String id, OtpKey key) {
      this.id = id;
      this.key = key;
    }
  }

  public static void main(String[] args) {
    Vertx.vertx().deployVerticle(new Foo());
  }

  private final Map<String, DBEntry> DB = new HashMap<>();

  private static final String ID = "Paulo";

  @Override
  public void start() {

    OtpKeyGenerator keyGen = OtpKeyGenerator.create();
    HotpAuth hotp = HotpAuth.create(new HotpAuthOptions());

    Router app = Router.router(vertx);
    // for form data parsing
    app.route().handler(BodyHandler.create());

    app.get("/register")
      .handler(ctx -> {
        OtpKey otpKey = keyGen.generate();

        System.out.println(otpKey.getBase32());
        // Create user in the database
        DB.put(ID, new DBEntry(ID, otpKey));

        URI uri = AuthenticatorUriGenerator.create().generateHotpUri(otpKey, "vertx_hotp", "user_1", "service_1");

        ctx.response()
          .putHeader("Content-Type", "image/png")
          .end(
            Buffer.buffer(
              QRCode
                .from(uri.toString())
                .to(ImageType.PNG)
                .withSize(512, 512)
                .stream()
                .toByteArray()));

      });

    app.post("/verify")
      .handler(ctx -> {
        String token = ctx.getBodyAsJson().getString("token");

        DBEntry entry = DB.get(ID);

        JsonObject principal = new JsonObject()
          .put("identifier", entry.id)
          .put("key", entry.key.getBase32())
          .put("counter", entry.counter);

        hotp.requestHotp(User.create(principal), requestHotp -> {
          if (requestHotp.failed()) {
            ctx.fail(requestHotp.cause());
          } else {
            hotp.authenticate(new HotpCredentials(ID, token))
              .onFailure(ctx::fail)
              .onSuccess(user -> {
                // Update user data
                entry.counter = user.attributes().getInteger("counter");
                DB.put(ID, entry);
                ctx.json(new JsonObject().put("verified", true));
              });
          }
        });
      });

    vertx.createHttpServer()
      .requestHandler(app)
      .listen(8080)
      .onFailure(Throwable::printStackTrace)
      .onSuccess(server -> {
        System.out.println("Server listening: http://localhost:" + server.actualPort());
      });
  }
}
```

@pmlopes Made changes to store the counter upon successful authentication. Now all my generated codes are working correctly. Could you try some more with current changes.

2021-06-23 19:08 UTC, otricadziziusz commented
@pmlopes Yes, to test the implementation, I used Google Authenticator.

2021-07-22 14:24 UTC, pmlopes commented
Closing as the work continued on #490 and #491 and it has been merged.

2021-07-22 14:24 UTC, closed without merging