JWK max age property added
eclipse-vertx/vertx-auth pull request #572
Opened 2022-07-11 16:28 UTC by Vorimo

Motivation: https://github.com/vert-x3/vertx-auth/issues/571

2022-07-12 07:03 UTC, vietj commented
@pmlopes can you revi'ew this PR ?

2022-07-12 15:05 UTC, pmlopes requested changes
Can we confirm that we always use millis in config and change the docs and logic to expect always millis?

2022-07-12 15:05 UTC, pmlopes commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java
> +  private static final long JWK_DEFAULT_AGE = 1L;
Shouldn't this be `-1`? Disabled by default

2022-07-12 15:05 UTC, pmlopes commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java
> +  //seconds of JWKs lifetime
I believe all other time related config values are millisecond based, we should keep it consistent, but I'm not 100% sure about this

2022-07-13 08:30 UTC, Vorimo commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java
> +  private static final long JWK_DEFAULT_AGE = 1L;
Initially we discussed it to be 1, but if you think so, let's do -1

2022-07-13 08:52 UTC, Vorimo commented
@pmlopes it could be done if we are gonna expect `maxAge` header as millis, since we have `leeway` in millis. Or I can convert `maxAge` to millis and expect a new property in millis already

2022-07-13 13:04 UTC, pmlopes commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java
> +  private static final long JWK_DEFAULT_AGE = 1L;
`1` is too short, depending on the unit, it would mean that we would have a repeating timer every `sec/millisecond` refreshing keys. So usually we use `-1` for disabled, and any positive value for enable, although 0 and 1 are very small values for any one...

2022-07-13 13:15 UTC, pmlopes commented
@Vorimo yes, you're right! Let's use `seconds` as that's the unit used byt JWTOptions and user leeway. I think we should have an setter like:

```java
public Oauth2Options setJwkMaxAgeInSeconds(int seconds) { ... }
```

Like we do in `JWTOptions`: 

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/java/io/vertx/ext/auth/JWTOptions.java#L103-L111

As a second PR we could align the remaining timing references to seconds, or if explicitly needed to be millis make it part of the name of the methods.

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-webauthn/src/main/java/io/vertx/ext/auth/webauthn/WebAuthnOptions.java#L364-L376

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-otp/src/main/java/io/vertx/ext/auth/otp/totp/TotpAuthOptions.java#L30

to mention a few...

2022-07-14 07:53 UTC, Vorimo commented
@pmlopes done

2022-07-14 19:17 UTC, pmlopes approved these changes

2022-07-15 09:08 UTC, merged