Minor auth logging edits
eclipse-vertx/vertx-auth pull request #644
Opened 2023-05-07 11:29 UTC by matthudsonatx

Motivation:

Improve auth logging.

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2023-05-09 13:39 UTC, tsegismont reviewed
Thank you, waiting for @pmlopes feedback

2023-05-09 13:39 UTC, tsegismont commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java
> +                LOG.info(String.format("Introspected client_id (%s) doesn't match configured client_id (%s)", clientId, json.getString("client_id")));
@pmlopes afaik `client_id` is not sensitive info but would appreciate your thoughts on the ability to log it?

2023-05-09 13:39 UTC, tsegismont commented
@matthudsonatx can you please signe the Eclipse Contributor Agreement?

2023-05-10 07:30 UTC, pmlopes commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java
> +                LOG.info(String.format("Introspected client_id (%s) doesn't match configured client_id (%s)", clientId, json.getString("client_id")));
I agree, I think it should be better to lower the level to debug to include that info, to avoid injecting user input into the logs.

2023-05-10 07:32 UTC, pmlopes requested changes
change is fine but the logging of user input should only be done with debug level. To avoid potential attacks like large crafted `client_id` values filling the logs

2023-05-10 14:20 UTC, matthudsonatx commented
I have signed the Eclipse Contributor Agreement. I'll send a PR with log level changed to debug shortly.

2023-05-10 14:34 UTC, matthudsonatx commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java
> +                LOG.info(String.format("Introspected client_id (%s) doesn't match configured client_id (%s)", clientId, json.getString("client_id")));
Please see most recent commit

2023-05-10 15:04 UTC, tsegismont commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java
> +                LOG.debug(String.format("Configured client_id: %s", json.getString("client_id")));
The log level should be checked to avoid creating strings if the level is info and above.

2023-05-10 18:37 UTC, matthudsonatx commented on vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java
> +                LOG.debug(String.format("Configured client_id: %s", json.getString("client_id")));
Please see latest commit

2023-05-11 09:36 UTC, tsegismont approved these changes
LGTM, thank you @matthudsonatx

2023-05-11 14:16 UTC, merged